import type { Metadata } from "next";
import "./ui/globals.css";

import { lato, nunito, openSans } from "./ui/fonts";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "SynthLauncher",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${openSans.variable} ${lato.variable} ${nunito.variable} antialiased`}
      >
        {/* Navbar */}
        <Navbar />

        {children}

        {/* Footer */}
        <Footer />
      </body>
    </html>
  );
}
