import type { Metadata } from "next";
import "../../ui/globals.css";

import { lato, nunito, openSans } from "../../ui/fonts";

export const metadata: Metadata = {
  title: "SynthLauncher",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${openSans.variable} ${lato.variable} ${nunito.variable}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
